# Apriori

In [1]:
pip install mlxtend

Requirement already satisfied: mlxtend in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (1.18.0)
Requirement already satisfied: numpy>=2.3.5 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (2.4.6)
Requirement already satisfied: pandas>=2.3.3 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (3.0.3)
Requirement already satisfied: scikit-learn>=1.8.0 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (3.11.0)
Requirement already satisfied: joblib>=1.5.2 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
# dataset of transaction
transactions = [
    ['Milk','Butter','Bread'],
    ['Milk','Bread'],
    ['Bread','Butter','Eggs'],
    ['Butter','Eggs'],
    ['Bread','Butter','Juice']
]

In [4]:
# EDA: Convert the transaction data into a one-hot encoded DataFrame
# Data Cleaning: Convert the transaction data into a one-hot encoded DataFrame
# Label encoding: Convert the transaction data into a one-hot encoded DataFrame 
# Algorithm cannot read words, so we need to convert the transaction data into a one-hot encoded DataFrame. One-hot encoding is a process of converting categorical data into a binary matrix. In this case, we will convert the transaction data into a binary matrix where each row represents a transaction and each column represents an item. If an item is present in a transaction, the corresponding cell will be 1, otherwise it will be 0.

te = TransactionEncoder()

#te_ary = te.fit(transactions).transform(transactions)
te_array = te.fit_transform(transactions)

# create a dataframe of these encoded transaction along with the table header
df_transactions = pd.DataFrame(te_array, columns=te.columns_)
display(df_transactions)

   Bread  Butter   Eggs  Juice   Milk
0   True    True  False  False   True
1   True   False  False  False   True
2   True    True   True  False  False
3  False    True   True  False  False
4   True    True  False   True  False

In [5]:
# Help frequently bought items in the transaction data using the Apriori algorithm. The Apriori algorithm is a classic algorithm used in data mining for learning association rules. It is used to find frequent itemsets in a dataset and derive association rules from them. The algorithm uses a breadth-first search strategy to count the support of itemsets and prune the search space based on the minimum support threshold.
# run the Apriori algorithm on the one-hot encoded DataFrame to find frequent itemsets with a minimum support of 0.4

frequent_itemsets = apriori (df_transactions, # the one-hot encoded DataFrame
                            min_support=0.4, # minimum support of 0.4 means that the itemset must appear in at least 40% of the transactions
                            use_colnames=True) # use_colnames=True means that the itemsets will be returned as a list of items instead of a list of column indices

In [6]:
frequent_itemsets

   support                    itemsets
0      0.8          frozenset({Bread})
1      0.8         frozenset({Butter})
2      0.4           frozenset({Eggs})
3      0.4           frozenset({Milk})
4      0.6  frozenset({Butter, Bread})
5      0.4    frozenset({Milk, Bread})
6      0.4   frozenset({Butter, Eggs})

In [7]:
clean_itemsets = frequent_itemsets['itemsets']

In [8]:
clean_itemsets

0            frozenset({Bread})
1           frozenset({Butter})
2             frozenset({Eggs})
3             frozenset({Milk})
4    frozenset({Butter, Bread})
5      frozenset({Milk, Bread})
6     frozenset({Butter, Eggs})
Name: itemsets, dtype: object

In [10]:
# Generate association rules from the frequent itemsets using the association_rules function. The association_rules function takes in the frequent itemsets and generates a set of rules based on the specified metric and threshold. In this case, we are using confidence as the metric and a minimum threshold of 0.7.
# rules to find what is likely going to be bought together. The association rules are generated based on the frequent itemsets found in the previous step. The rules are generated based on the specified metric and threshold. In this case, we are using confidence as the metric and a minimum threshold of 0.7. Confidence is a measure of how often the rule has been found to be true. It is calculated as the support of the itemset divided by the support of the antecedent.
rules = association_rules(frequent_itemsets, # dataframe of itemsets & supportgenerated by the apriori algorithm 
                          metric="confidence", # metric to evaluate the quality of the rules. In this case, we are using confidence as the metric. Confidence is a measure of how often the rule has been found to be true. It is calculated as the support of the itemset divided by the support of the antecedent.
                          min_threshold=0.7) # at least 70% confidence means that the rule must be true at least 70% of the time

final_table = rules[["antecedents", "consequents", "support", "confidence", "lift"]]

display(final_table)

           antecedents          consequents  support  confidence    lift
0  frozenset({Butter})   frozenset({Bread})      0.6        0.75  0.9375
1   frozenset({Bread})  frozenset({Butter})      0.6        0.75  0.9375
2    frozenset({Milk})   frozenset({Bread})      0.4        1.00  1.2500
3    frozenset({Eggs})  frozenset({Butter})      0.4        1.00  1.2500

In [16]:
# test our system

current_cart = frozenset({'Bread'})

# find the consequents based on the antecedents

recommendations = rules[rules['antecedents'] == frozenset(current_cart)]
# recommendations = rules[rules['antecedents'] == current_cart]
recommendations.head()
#print(recommendations)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,frozenset({Bread}),frozenset({Butter}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75